<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Protos\cache.proto" />
    <None Remove="Protos\google\api\annotations.proto" />
    <None Remove="Protos\google\api\http.proto" />
    <PackageReference Include="Google.Protobuf" Version="3.27.3" />
    <PackageReference Include="Grpc.Net.ClientFactory" Version="2.65.0" />
   
    <PackageReference Include="Grpc.Tools" Version="2.65.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
   
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
   
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.2" />
   
    
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\cache.proto">
      <GrpcServices>Client</GrpcServices>
    </Protobuf>
    <Protobuf Include="Protos\google\api\annotations.proto" GrpcServices="Client" />
    <Protobuf Include="Protos\google\api\http.proto" GrpcServices="Client" />
  </ItemGroup>
</Project>
