apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: file-cache-deploy
  name: file-cache-deploy
  namespace: grpc-cache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: file-cache-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: file-cache-deploy
    spec:
      volumes:
      - name: pv-vol
        persistentVolumeClaim:
          claimName: pv-cache-claim
      containers:
      - image: venkateshsrini3/file-cache:dnslg
        name: file-cache
        volumeMounts:
        - name: pv-vol
          mountPath: /app/cacheDir
        ports:
        - containerPort: 5275
          name: grpc
        env:
        - name: "http2Port"
          value: "5275"
        - name: "podName"
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
# nslookup command to test deployment {k exec dnsutils -n grpc-cache -- nslookup file-cache-grpc-service}
