apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: file-cache-deploy
  name: file-cache-grpc-service
  namespace: grpc-cache
spec:
  ports:
  - port: 5275
    protocol: TCP
    targetPort: 80
  selector:
    app: file-cache-deploy
  clusterIP: None
status:
  loadBalancer: {}
