apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: file-cache-deploy
  name: file-cache-http-service
spec:
  ports:
  - port: 7007
    protocol: TCP
    targetPort: 7007
  selector:
    app: file-cache-deploy
  type: LoadBalancer
status:
  loadBalancer: {}
