apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: file-cache-deploy
  name: file-cache-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-cache-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: file-cache-deploy
    spec:
      volumes:
      - name: pv-vol
        persistentVolumeClaim:
          claimName: pv-cache-claim
      containers:
      - image: venkateshsrini3/file-cache-transcoding
        name: file-cache
        volumeMounts:
        - name: pv-vol
          mountPath: /app/cacheDir
        ports:
        - containerPort: 5275
          name: gRpc
        - containerPort: 7007
          name: http