apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cache-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/c/local-file-access"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-cache-claim
spec:
  volumeName: pv-cache-volume
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi