apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: file-cache-client-deploy
  name: file-cache-client-service
  namespace: grpc-cache
spec:
  ports:
  - port: 6009
    protocol: TCP
    targetPort: 80
  selector:
    app: file-cache-client-deploy
  type: LoadBalancer
status:
  loadBalancer: {}
