apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: file-cache-client-deploy
  name: file-cache-client-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-cache-client-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: file-cache-client-deploy
    spec:
      containers:
      - image: venkateshsrini3/file-cache-client
        name: file-cache-client
        ports:
        - containerPort: 80
        env:
        - name: CacheService__url
          value: http://file-cache-grpc-service.default.svc.cluster.local:5275